# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwars', '0002_remove_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='Ime', max_length=250),
        ),
    ]
