# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwars', '0003_player_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hasDrawed',
            field=models.BooleanField(default=False),
        ),
    ]
