# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwars', '0003_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='judgeable',
        ),
        migrations.AlterField(
            model_name='game',
            name='drawing1',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='drawing2',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
