# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwars', '0006_player_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='drawing',
            field=models.TextField(null=True),
        ),
    ]
