# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwars', '0007_auto_20170325_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='drawing',
        ),
        migrations.AddField(
            model_name='game',
            name='drawing1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='drawing2',
            field=models.TextField(null=True),
        ),
    ]
