# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwars', '0005_game_judgable'),
        ('pixelwars', '0008_auto_20170325_1439'),
    ]

    operations = [
    ]
