# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwars', '0009_merge_20170325_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourney',
            old_name='name',
            new_name='theme',
        ),
        migrations.AddField(
            model_name='tourney',
            name='drawing1',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='drawing2',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='drawing3',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='drawing4',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneyplayer1', to='pixelwars.Player'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneyplayer2', to='pixelwars.Player'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='player3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneyplayer3', to='pixelwars.Player'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='player4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneyplayer4', to='pixelwars.Player'),
        ),
    ]
