# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwars', '0012_auto_20170326_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='player5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneyplayer5', to='pixelwars.Player'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='player6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneyplayer6', to='pixelwars.Player'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='player7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneyplayer7', to='pixelwars.Player'),
        ),
    ]
